version: '3'

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - flyway
    command: ["npm", "start"]
    environment:
      - YAHOO_API_KEY=${YAHOO_API_KEY}
      - YAHOO_API_HOST=${YAHOO_API_HOST}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}

  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: yourUsername
      POSTGRES_PASSWORD: yourPassword
      POSTGRES_DB: yourDatabase
    ports:
      - "5432:5432"

  flyway:
    image: boxfuse/flyway:latest-alpine
    volumes:
      - ./db/migrations:/flyway/sql
    depends_on:
      - postgres
    command: ["-url=jdbc:postgresql://localhost:5432/yourDatabase", "-user=yourUsername", "-password=yourPassword", "-connectRetries=60", "migrate"]
    network_mode: "host"